import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/NavBar/NavBar";
import Footer from "@/component/Footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
          <div className="container">
            <Navbar />
            {children}
            <Footer />
          </div>
      </body>
    </html>
  );
}
